name: HavanaWarps
version: ${project.version}
main: com.danielgulic.havanawarps.HavanaWarps
api-version: 1.13
authors: [jellz]
depend: [SmartInvs]
commands:
  warps:
    permission: havanawarps.warps
    description: Open warps menu
    usage: /warps