name: HavanaWarps
version: 1.0-SNAPSHOT
main: com.danielgulic.havanawarps.HavanaWarps
api-version: 1.13
authors: [jellz]
depends: [SmartInvs]
commands:
  warps:
    description: Open warps menu
    usage: /warps